### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by aaiyer**

### CODE REVIEW

**Comment by aaiyer** [comment]
I added Python 3 support by checking out https://code.google.com/p/ctypesgen/source/browse/branches/python-3/ in ctypesgen-3 -- then I changed all maxint to maxsize (Python 3 doesn't have maxint). Then I made setup.py pick the correct ctypesgen depending on python version

**Comment by coleifer** [comment]
I was able to build the shared library using your branch, but it looks like the library is named `libvedis.cpython-34m.so` when it needs to be `libvedis.so`. That should be easy enough to fix, though.

The other thing is when I tried to initialize `Vedis`, I received the following traceback:

```python
In [1]: from vedis import *

In [2]: v = Vedis()
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-2-1886c63818ff> in <module>()
----> 1 v = Vedis()

/home/charles/tmp/scrap/vds/vedis-python/build/lib.linux-x86_64-3.4/vedis/core.py in __init__(self, database, open_manually)
    110         self._command_registry = {}
    111         if not open_manually:
--> 112             self.open()
    113 
    114     def open(self):

/home/charles/tmp/scrap/vds/vedis-python/build/lib.linux-x86_64-3.4/vedis/core.py in open(self)
    113 
    114     def open(self):
--> 115         rc = vedis_open(byref(self._vedis), self.database)
    116         if rc != VEDIS_OK:
    117             raise Exception('Unable to open Vedis database')

ArgumentError: argument 2: <class 'NameError'>: name 'unicode' is not defined
```

If I remove `unicode` from the `isinstance` check, I get this traceback instead:

```python
In [2]: v = Vedis()
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-2-1886c63818ff> in <module>()
----> 1 v = Vedis()

/home/charles/tmp/scrap/vds/vedis-python/build/lib.linux-x86_64-3.4/vedis/core.py in __init__(self, database, open_manually)
    110         self._command_registry = {}
    111         if not open_manually:
--> 112             self.open()
    113 
    114     def open(self):

/home/charles/tmp/scrap/vds/vedis-python/build/lib.linux-x86_64-3.4/vedis/core.py in open(self)
    113 
    114     def open(self):
--> 115         rc = vedis_open(byref(self._vedis), self.database)
    116         if rc != VEDIS_OK:
    117             raise Exception('Unable to open Vedis database')

ArgumentError: argument 2: <class 'TypeError'>: bytes or integer address expected instead of str instance

```

No offense but did you even test this?

**Comment by aaiyer** [comment]
I am not sure what you error are. If you look at what changes I made in the diff, you can see,
  1. I renamed ctypesgen to ctypesgen-2
  2. I checked out https://code.google.com/p/ctypesgen/source/browse/branches/python-3/ to ctypesgen-3 and replaced all sys.maxint to sys.maxsize
  3. I changed setup.py and renamed python to python2 in subprocess.check_call and declared ctypesgen_dir = 'ctypesgen-%d' % sys.version_info[0]

From working on it for a bit of time -- it seems to be a bug with the python-3 branch of ctypesgen. As ctypesgen is not really maintained, either I have to fix ctypesgen or rewrite your module's like to the library. Sadly, I am afraid I do not have much time to do that. My bad, sorry for wasting your time. Sadly, I am afraid I do not have much time to do that right now. My bad, sorry for wasting your time.

**Comment by coleifer** [comment]
I was able to view the diff and your changes made sense to me. I was just wondering if you'd actually tested them, because they did not seem to work for me when I tested it. Don't feel bad for wasting my time! Just wasn't sure if I was missing something or you had actually been able to get it working.

**Pull request closed without merging**
